import math

X_SIZE = 5
Y_SIZE = 5

BORDER_SIZE = 10


HEX_RADIUS = 50
RADIUS_I = HEX_RADIUS * math.sqrt(3) / 2
HEIGHT_D = RADIUS_I * math.sqrt(3)

WINDOW_WIDTH = 2 * BORDER_SIZE + RADIUS_I + X_SIZE * 2 * RADIUS_I
WINDOW_HEIGHT = 2 * BORDER_SIZE + 2 * RADIUS_I + (Y_SIZE - 1) * HEIGHT_D


WINDOW_HEIGHT = int(WINDOW_HEIGHT)
WINDOW_WIDTH = int(WINDOW_WIDTH)